name: Build Python Project

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./path/to/your/project

      - name: Build
        run: |
          python build.py  # Replace with your build command
        working-directory: ./path/to/your/project

      - name: Save build log
        run: |
          cp build.log $GITHUB_WORKSPACE/build.log
        working-directory: ./path/to/your/project

      - name: Upload log file
        uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: $GITHUB_WORKSPACE/build.log
